version: '3'
services:
  bitwarden-backup:
    build: .
    container_name: gangz1o/bitwarden-backup:latest
    environment:
      - BW_HOST=${BW_HOST}
      - BW_EMAIL=${BW_EMAIL}
      - BW_PASSWORD=${BW_PASSWORD}
      - BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}
      - BACKUP_SCHEDULE=0 */8 * * *
      - AUTO_DECRYPT=${AUTO_DECRYPT:-false}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
      - TZ=Asia/Shanghai
    volumes:
      - ./backup:/backup
    restart: unless-stopped
